### ISSUE TITLE
Automatic scratch config's c_flags does not include extra_cflags

### ISSUE THREAD

**Issue by LagoLunatic** [encounter/dtk-template#24]
It includes all of the shared `cflags` but not the object-specific `extra_cflags`.

Example fix: https://github.com/zeldaret/tww/commit/7916599cad12c8a6809946ac07e8a2479f38a5cc

**Comment by encounter** [comment]
That fix looks good, I’d accept it as a PR if you were willing to open one. Otherwise I’ll copy it when I’m able.
