### ISSUE TITLE
Build failed with "Linker Error: #   Multiple output section name '.rodata' not allowed in linker command file."

### ISSUE THREAD

**Issue by gwoonryan** [encounter/dtk-template#26]
Hi, after following all the steps in the "getting_started.md" file until the first analysis, the program crashed with this error:
<pre>
> PS C:\Users\ryanv\Desktop\code\wii\decomp toolkit\dtk-template> ninja
> [1/2] SPLIT config\RSPE01\config.yml
>  INFO Loading config\RSPE01\config.yml
>  INFO Loading and analyzing 1 module (using 1 thread)
>  INFO Initial analysis completed in 1.118s (found 14119 functions)
>  INFO Rebuilding relocations and splitting
>  WARN module{name=main id=0}: Alignment for auto_11_804BF314_sbss .sbss expected 8, but starts at 11:0x804BF314
>  INFO Splitting completed in 2.845s (wrote 518 objects)
>  INFO Total time: 3.969s
> [2/2] RUN configure.py
> [1/4] LINK build\RSPE01\main.elf
> FAILED: build/RSPE01/main.elf
> build\compilers\GC\1.3.2\mwldeppc.exe -fp hardware -nodefaults -lcf build\RSPE01\ldscript.lcf -o build\RSPE01\main.elf @build\RSPE01\main.elf.rsp
>  build\compilers\GC\1.3.2\mwldeppc.exe Linker Error:
>     Multiple output section name '.rodata' not allowed in linker command file.
>  build\compilers\GC\1.3.2\mwldeppc.exe Linker Alert:
>     Link failed.
> 
> Errors caused tool to abort.
> ninja: build stopped: subcommand failed.
</pre>

I am trying to decompile Wii Sports, is this an issue on my part, or is it a bug in the decompiler? 
I have attached the generated splits, the generated symbols and my config.

[splits.txt](https://github.com/user-attachments/files/16404695/splits.txt)
[symbols.txt](https://github.com/user-attachments/files/16404696/symbols.txt)
[config - copy.txt](https://github.com/user-attachments/files/16404700/config.-.copy.txt)

**Comment by encounter** [comment]
One of the rodata sections that dtk detected is actually `.BINARY` (note the existing Wii Sports decomp [here](https://github.com/kiwi515/ogws/blob/master/ldscript.lcf#L16), it has it labeled `.file`, but `.BINARY` is the correct section name).

You can rename that section in splits.txt, delete symbols.txt and let it regenerate.

**Comment by gwoonryan** [comment]
Thanks for the help! It actually made it work, but it is probably better if I use the already made decomp, but I just cant find "codewarrior/GC/3.0" can you maybe help we with this in some way or another?

**Comment by encounter** [comment]
You’ll already have it under `build/compilers`, dtk-template downloads it automatically.

**Comment by gwoonryan** [comment]
The decompilation specifically asks for the versions "2.7, 3.0 and 3.0a3" I found 2.7 and 2.0a3 there but not 3.0 unfortunately... Is it supposed to be there?

**Comment by encounter** [comment]
I think 3.0a5 is the right version for that, but I’m unsure.

**Comment by gwoonryan** [comment]
I think this actually works, I will test some more but thank you so much!

**Comment by encounter** [comment]
No problem!
