### ISSUE TITLE
Support ISO For Original Files

### ISSUE THREAD

**Issue by NWPlayer123** [encounter/dtk-template#31]
It would make things a lot simpler if we could just shove the entire iso into orig/GAMEID and have nod handle extracting any necessary files on build, instead of requiring dolphin (or GCRebuilder) to extract them in the README.

Ideally it wouldn't even have to "extract" them, it can just stream the data from the iso as it's building.

**Comment by encounter** [comment]
Added with decomp-toolkit v1.1.2 and https://github.com/encounter/dtk-template/commit/ff6be416c6ba7148e07bb8228394da3b4a5373b3
