### ISSUE TITLE
decompctx.py: include pattern does not support comments

### ISSUE THREAD

**Issue by elijah-thomas774** [encounter/dtk-template#39]
with the clangd addition, includes can be seen to have comments such as:
```C
#include "my_file.h" // IWYU pragma: export
```

The current `include_pattern` regex in decompctx.py does not account for this.

A solution could be to allow any(non-capture?) characters until end of line after the pattern is met?

**Comment by encounter** [comment]
Fixed in 6d59f31a80a4e8b900e7558d4a2842fd14e054d1
